<%
	Response.ContentType = "text/css"
%>

<!-- #include file="../inc/skin.asp" -->

<%
'/********************************************************/
'/*DEFINIÇÕES DE CORES E ESTILO DO TERMINAL WEB  0509 ASP*/
'/********************************************************/
response.write "* {"
response.write "	padding: 0;"
response.write "	border: 0;"
response.write "	margin: 0;"
response.write "}"

response.write "table, tr, td, p, font, a { font: " & css_geral_fonte & "; color:" & css_geral_cor_fonte & "; }"
 
response.write "table {"
response.write "	border-spacing: 0;"
response.write "}"

response.write "td {"
response.write "	padding: 2px;"
response.write "}"

response.write "body{"
response.write "	font: " & css_geral_fonte & "; color: " & css_geral_cor_fonte & ";"
response.write "	background: " & css_cor_fundo_corpo & ";"
response.write "}" 

response.write "input[type='text'],"
response.write "input[type='password']"
response.write "{"
response.write "	padding: 1px;"
response.write "	font: " & css_geral_fonte & ";"
response.write "	border: 1px solid #006699;"
response.write "	background-color: #FFFFFF;"
response.write "	height: 18px;"
response.write "}"

response.write "input[type='button'],"
response.write "input[type='submit']"
response.write "{ "
response.write "	font: " & css_geral_botao_tipo_fonte & ";"
response.write "	border: 1px solid " & css_geral_botao_cor_margem & ";"
response.write "	background-color: " & css_geral_botao_cor_fundo & ";"
response.write "	color: " & css_geral_botao_cor_fonte & ";"
response.write "	height: 22px;"
response.write "	padding-left: 8px;"
response.write "	padding-right: 8px;"
response.write "	cursor: pointer;"
response.write "}"

response.write "textarea "
response.write "{ "
response.write "	font: " & css_geral_fonte & ";"
response.write "	border: 1px solid #006699;"
response.write "	background-color: #FFFFFF;"
response.write "}"

response.write "select"
response.write "{"
response.write "	border: 1px solid #006699;"
response.write "	background-color: #FFF;"
response.write "	height: 22px;"
response.write "}"

response.write "#divNewMain"
response.write "{"
response.write "	width: 970px;"
response.write "	margin-left: auto;"
response.write "	margin-right: auto;"
response.write "	background-color: " & css_cor_fundo_centro & ";"
response.write "	padding: 0px 10px 0px 10px;"
response.write "}"

response.write "#divTituloPesquisa "
response.write "{"
response.write "	margin: auto;"
response.write "	width: 95%;"
response.write "	height: 20px;"
response.write "	text-align: left;"
response.write "	padding: 5px;"
response.write "	background-color: " & css_titulo_pesquisa_cor_fundo & ";"
response.write "	color: " & css_titulo_pesquisa_cor & ";"
response.write "}"

response.write "#divTituloPesquisa a,"
response.write "#divTituloPesquisa a:hover"
response.write "{"
response.write "	color: #fff;"
response.write "}"

response.write ".transparent-icon {"
response.write "	background-color: " & css_geral_cor & ";"
response.write "	vertical-align: text-bottom;"
response.write "}"

response.write ".td_cabecalho_banner"
response.write "{"
response.write "	border: 0;"
response.write "	color: #000;"
response.write "	height: 120px;"
response.write "	background-image: url('../imagens/banner.jpg');"
response.write "	background-repeat: no-repeat;"
response.write "	background-position: center center;"
response.write "}"

response.write ".td_cabecalho_banner span"
response.write "{"
response.write "	font: " & css_fonte_banner & ";"
response.write "	font-size: 30px;"
response.write "	font-weight: Bold;"
response.write "	color:" & css_cor_fonte_banner & ";"
response.write "}"

response.write ".input_busca{"
response.write "	font: " & css_geral_fonte & ";"
response.write "	border: 1px solid #7F9DB9;"
response.write "}"

response.write ".td_corpo_externo{"
response.write "	text-align: center;"
response.write "	vertical-align: top;"
response.write "	border: 0;"
response.write "}"

response.write ".td_corpo{"
response.write "	width: 100%;"
response.write "	height: 306px;"
response.write "	border: none;"
response.write "}"

response.write ".grid{"
response.write "	color: #000;"
response.write "	font: " & css_geral_fonte & ";"
response.write "}"

response.write ".td_grid_miniatura{"
response.write "	width: 110px;"
response.write "	padding: 0;"
response.write "	vertical-align: top;"
response.write "	text-align: center;"
response.write "}"

response.write ".tr_grid_cabecalho{"
response.write "	background-color: " & css_geral_cor & ";"
response.write "}"

response.write ".td_grid_cabecalho{"
response.write "	color: " & css_grid_cabecalho_cor_fonte & ";"
response.write "}"

response.write ".td_campo {"
response.write "    text-align: right;"
response.write "	background-color: " & css_grid_campo_cor_fundo & ";"
response.write "	border: none;"
response.write "	border-top: 1px solid #cecece;"
response.write "	padding: 5px;"
response.write "	color: " & css_grid_campo_cor_fonte & ";"
response.write "}"

response.write ".td_valor {"
response.write "	background-color: " & css_grid_valor_cor_fundo & ";"
response.write "	color: " & css_grid_valor_cor_fonte & ";"
response.write "	font: " & css_geral_fonte & ";"
response.write "	border-top: 1px solid #eee;"
response.write "	padding: 5px;"
response.write "	text-align: left;"
response.write "}"

response.write ".link_valor { color: " & css_link_grid_valor_cor & "; font-size: " & css_link_geral_tamanho_fonte & "; text-decoration: none; font-weight: 500;}"
response.write ".link_valor:visited,.link_valor:active { color: " & css_link_grid_valor_cor & "; }"
response.write ".link_valor:hover { color: " & css_link_grid_valor_cor_hover & "; }"

response.write ".link_menu { color: " & css_link_menu_cor & "; font-size: " & css_link_geral_tamanho_fonte & "; text-decoration: none; }"
response.write ".link_menu:visited,.link_menu:active { color: " & css_link_menu_cor & "; }"
response.write ".link_menu:hover { color: " & css_link_menu_cor_hover & "; }"

response.write ".link_login"
response.write "{"
response.write "	color: " & css_link_menu_cor & ";"
response.write "	font-size: " & css_link_geral_tamanho_fonte & ";"
response.write "	text-decoration: none;"
response.write "	float: right;"
response.write "}"

response.write ".link_midias:link { color: " & css_link_midias_cor & "; font-size: " & css_link_geral_tamanho_fonte & "; text-decoration: none; font-weight: 600;}"
response.write ".link_midias:visited,.link_midias:active { color: " & css_link_midias_cor & "; }"
response.write ".link_midias:hover { color: " & css_link_midias_cor_hover & "; }"

response.write ".destaca_palavras {"
response.write "	background-color: " & css_destaca_palavras & ";"
response.write "}"

response.write ".popup_cabecalho_background"
response.write "{"
response.write "	background-color: " & css_geral_cor & ";"
response.write "}"

response.write ".popup_cabecalho_fonte"
response.write "{"
response.write "	color: #FFFFFF;"
response.write "	line-height: 26px;"
response.write "	vertical-align: middle;"
response.write "}"

response.write "	.popup_cabecalho_fonte > span"
response.write "	{"
response.write "		font-size: 13px;"
response.write "		padding-top: 2px;"
response.write "		padding-left: 5px;"
response.write "	}"
	
response.write ".popup"
response.write "{"
response.write "	background-color: #fff;"
response.write "	text-align: center;"
response.write "	padding-top: 10px;"
response.write "}"

response.write ".esquerda"
response.write "{"
response.write "	text-align: left;"
response.write "}"

response.write ".centro"
response.write "{"
response.write "	text-align: center;"
response.write "}"

response.write ".direita"
response.write "{"
response.write "	text-align: right;"
response.write "}"

response.write ".DivLogin"
response.write "{"
response.write "    width: 320px; /* Tamanho da Largura da Div */"
response.write "	height: 200px; /* Tamanho da Altura da Div */"
response.write "    position: absolute; "
response.write "    top: 50%; "
response.write "    margin-top: -100px; /* ou seja ele pega 50% da altura tela e sobe metade do valor da altura no caso 100 */"
response.write "    left: 50%;"
response.write "    margin-left: -140px; /* ou seja ele pega 50% da largura tela e diminui  metade do valor da largura no caso 250 */"
response.write "    z-index: 999;"
response.write "    display: none;"
response.write "}"

response.write "#screen"
response.write "{"
response.write "    position: absolute;"
response.write "    left: 0;"
response.write "    top: 0;"
response.write "    background: #333;"
response.write "}"

response.write ".input_login"
response.write "{"
response.write "	width: 130px;"
response.write "	height: 22px;"
response.write "}"

response.write ".button_login "
response.write "{"
response.write "	width: 70px;"
response.write "}"

response.write ".espacamento_login"
response.write "{"
response.write "    padding-left: 10px;"
response.write "}"

response.write ".nome_login"
response.write "{"
response.write "	font: " & css_geral_fonte & ";"
response.write "	text-decoration: none;"
response.write "	float: right;"
response.write "	padding-right : 10px;"
response.write "}"
%>