<%
'/********************************************************/
'/*   DEFINIÇÕES DE CORES E ESTILO DO TERMINAL WEB ASP   */
'/********************************************************/
response.write "<style type='text/css'><!--"

response.write "body, table, tr, td, p, font, a, select"
response.write "{"
response.write "    font-family: " & css_geral_fonte & ";"
response.write "}"
response.write "input[type='text'],"
response.write "input[type='password']"
response.write "{"
response.write "    font-size: " & css_geral_tamanho_fonte & "px;"
response.write "    font-family: " & css_geral_fonte & " !important;"
response.write "    border: 1px solid " & css_busca_inputs & ";"
response.write "}"
response.write "input[type='button']"
response.write "{"
response.write "    font-size: " & css_geral_botao_tamanho_fonte & "px;"
response.write "    font-family: " & css_geral_fonte & " !important;"
response.write "    border: 1px solid " & css_geral_botao_cor_margem & ";"
response.write "    background-color: " & css_geral_botao_background & ";"
response.write "    color: " & css_geral_botao_cor_fonte & ";"
response.write "}"
response.write "textarea"
response.write "{"
response.write "    font-size: " & css_geral_tamanho_fonte & "px;"
response.write "    font-family: " & css_geral_fonte & " !important;"
response.write "    border: 1px solid " & css_busca_inputs & ";"
response.write "}"
response.write "select"
response.write "{"
response.write "    border: 1px solid " & css_busca_inputs & ";"
response.write "}"
response.write ".tab_div"
response.write "{"
response.write "    background-color: " & css_geral_corpo_margem & ";"
response.write "}"
response.write ".td_cabecalho"
response.write "{"
response.write "    background-image: url(../imagens/" & css_imagem_banner & ");"
response.write "    background-position: center " & css_alinhamento_banner & ";"
response.write "}"
response.write ".span-menu-item{"
response.write "	background-color: " & css_menu_background & ";"
response.write "}"
response.write ".td_home"
response.write "{"
response.write "	background-image: url(../imagens/" & css_imagem_home & ");"
response.write "}"
response.write ".link_menu1:link,"
response.write ".link_menu1:visited,"
response.write ".link_menu1:active"
response.write "{ "
response.write "    color: " & css_menu_link_normal & ";"
response.write "    font-weight: " & css_menu_link_font_weight & ";"
response.write "}"
response.write ".link_menu1:hover"
response.write "{"
response.write "    color: " & css_menu_link_over & ";"
response.write "    font-weight: " & css_menu_link_font_weight & ";"
response.write "}"
response.write ".link_menu2:link,"
response.write ".link_menu2:visited,"
response.write ".link_menu2:active"
response.write "{"
response.write "    color: " & css_menu_link_normal & ";"
response.write "    font-weight: " & css_menu_link_font_weight & ";"
response.write "}"
response.write ".link_menu2:hover"
response.write "{"
response.write "    color: " & css_menu_link_over & ";"
response.write "    font-weight: " & css_menu_link_font_weight & ";"
response.write "}"
if css_geral_background_externo = "#000000" OR css_geral_background_externo = "#999999" then
    response.write ".link_prima:link,"
    response.write ".link_prima:visited"
    response.write "{"
    response.write "    color: #FFFFFF;"
    response.write "}"
else
    response.write ".link_prima:link,"
    response.write ".link_prima:visited"
    response.write "{"
    response.write "    color: #000000;"
    response.write "}"
end if
response.write ".link_prima:active,"
response.write ".link_prima:hover"
response.write "{"
response.write "    color: " & css_geral_link_servicos_over & ";"
response.write "}"
response.write ".link_serv:link,"
response.write ".link_serv:visited"
response.write "{"
response.write "    color: " & css_geral_link_servicos_normal & ";"
response.write "}"
response.write ".link_serv:hover,"
response.write ".link_serv:active"
response.write "{"
response.write "    color: " & css_geral_link_servicos_over & ";"
response.write "}"
response.write ".popup_cabecalho_background"
response.write "{"
response.write "    background-color: " & css_popup_cabecalho & ";"
response.write "}"
response.write ".popup_cabecalho_fonte"
response.write "{"
response.write "    color: " & css_popup_cabecalho_cor_fonte & ";"
response.write "}"
response.write "	.popup_cabecalho_fonte > span"
response.write "	{"
response.write "		font-size: " & css_geral_tamanho_fonte & "px;"
response.write "	}"
response.write ".td_col_grid"
response.write "{"
response.write "    background-color: " & css_detalhe_esquerda & ";"
response.write "}"
response.write "--></style>"
%>